const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={sources:[],source:'zho',channels:[],visible:[],current:null,mode:'all',availability:new Map(),favorites:load('favorites',[]),recent:load('recent',[]),blocked:new Set(load('blocked',[])),hls:null,testing:false,fullscreen:false};
let toastTimer;
function load(k,f){try{return JSON.parse(localStorage.getItem(k))??f}catch{return f}}
function save(k,v){localStorage.setItem(k,JSON.stringify(v))}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2000)}
function parseM3U(text){const result=[],seen=new Set();let meta=null;for(const raw of text.replace(/^\uFEFF/,'').split(/\r?\n/)){const line=raw.trim();if(line.startsWith('#EXTINF:')){const comma=line.indexOf(',');meta={name:comma>=0?line.slice(comma+1).trim():'未命名频道',group:(line.match(/group-title="([^"]*)"/)||[])[1]||'',logo:(line.match(/tvg-logo="([^"]*)"/)||[])[1]||''}}else if(/^https?:\/\//i.test(line)&&meta){if(!seen.has(line)&&!/xxx/i.test(meta.group)){seen.add(line);result.push({...meta,url:line})}meta=null}}return result}
function keyOf(c){return c.url}
function persist(){save('favorites',state.favorites);save('recent',state.recent);save('blocked',[...state.blocked])}
function remember(c){state.recent=state.recent.filter(x=>x.url!==c.url);state.recent.unshift(c);state.recent=state.recent.slice(0,20);persist()}
function setMode(mode){state.mode=mode;$$('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));render()}
function render(){const q=$('#search').value.trim().toLowerCase();let base=state.mode==='favorites'?state.favorites:state.mode==='recent'?state.recent:state.channels;base=base.filter(c=>!state.blocked.has(c.url)&&(!q||(c.name+' '+c.group).toLowerCase().includes(q))&&(state.mode!=='available'||state.availability.get(c.url)===true));state.visible=base;const shown=base.slice(0,500);$('#channels').innerHTML=shown.map((c,i)=>`<button class="channel focusable ${state.current?.url===c.url?'playing':''}" data-i="${i}"><span class="logo">${escapeHtml((c.name||'TV').slice(0,3))}</span><span><strong>${escapeHtml(c.name)}</strong><small>${escapeHtml(c.group||'直播频道')}</small></span><span>▶</span></button>`).join('');$('#summary').textContent=`${base.length} 个频道${base.length>500?' · 显示前 500 个':''}`;$$('.channel').forEach(b=>b.onclick=()=>play(state.visible[Number(b.dataset.i)]))}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function loadSource(refresh=false){$('#summary').textContent=refresh?'正在更新频道…':'正在读取频道…';try{const text=await window.mibox.loadSource(state.source,refresh);state.channels=parseM3U(text);state.availability.clear();setMode('all');toast(refresh?'频道已更新':'频道加载完成')}catch(e){toast(`加载失败：${e.message}`);render()}}
async function play(c){if(!c)return;state.current=c;remember(c);render();$('#empty').style.display='none';$('#loading').style.display='block';$('#nowTitle').textContent=c.name;$('#nowGroup').textContent=(c.group||'LIVE').toUpperCase();$('#favorite').textContent=state.favorites.some(x=>x.url===c.url)?'★ 已收藏':'☆ 收藏';const video=$('#video');try{if(state.hls){state.hls.destroy();state.hls=null}video.pause();video.removeAttribute('src');video.load();if(/\.m3u8($|\?)/i.test(c.url)&&window.Hls?.isSupported()){state.hls=new Hls({enableWorker:true,lowLatencyMode:true,maxBufferLength:30});state.hls.loadSource(c.url);state.hls.attachMedia(video);state.hls.on(Hls.Events.MANIFEST_PARSED,()=>video.play().catch(()=>{}));state.hls.on(Hls.Events.ERROR,(_e,d)=>{if(d.fatal){$('#loading').style.display='none';toast('频道暂时无法播放')}})}else{video.src=c.url;await video.play()} }catch(e){toast('播放失败，请换一个频道')} }
function next(delta){if(!state.visible.length)return toast('当前没有频道');let i=state.visible.findIndex(x=>x.url===state.current?.url);if(i<0)i=0;else i=(i+delta+state.visible.length)%state.visible.length;play(state.visible[i])}
async function testSources(){if(state.testing)return toast('正在测试中');if(!state.channels.length)return;state.testing=true;state.availability.clear();let index=0,done=0,good=0;const total=state.channels.length;$('#progress').textContent=`测试 0/${total}`;async function worker(){while(index<total&&state.testing){const c=state.channels[index++];const ok=await window.mibox.testStream(c.url);state.availability.set(c.url,ok);done++;if(ok)good++;if(done%8===0||done===total)$('#progress').textContent=`测试 ${done}/${total} · 可用 ${good}`}}await Promise.all(Array.from({length:8},worker));state.testing=false;$('#progress').textContent=`完成 · 可用 ${good}/${total}`;toast('直播源测试完成');if(state.mode==='available')render()}
async function openLocal(){const url=await window.mibox.openVideo();if(url)play({name:'本地视频',group:'本地文件',url})}
async function importM3U(){const data=await window.mibox.openPlaylist();if(!data)return;state.channels=parseM3U(data.text);state.source='local';$('#source').insertAdjacentHTML('beforeend',`<option value="local">${escapeHtml(data.name)}</option>`);$('#source').value='local';setMode('all');toast(`已导入 ${state.channels.length} 个频道`)}
function toggleFavorite(){if(!state.current)return toast('请先选择频道');const exists=state.favorites.some(x=>x.url===state.current.url);state.favorites=exists?state.favorites.filter(x=>x.url!==state.current.url):[state.current,...state.favorites];persist();$('#favorite').textContent=exists?'☆ 收藏':'★ 已收藏';if(state.mode==='favorites')render()}
function bind(){
  $('#source').onchange=e=>{if(e.target.value==='local')return;state.source=e.target.value;loadSource(false)};$('#search').oninput=render;$$('.tabs button').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
  $('#prev').onclick=()=>next(-1);$('#next').onclick=()=>next(1);$('#toggle').onclick=()=>{const v=$('#video');if(!state.current)return toast('请先选择频道');if(v.paused){v.play();$('#toggle').textContent='Ⅱ 暂停'}else{v.pause();$('#toggle').textContent='▶ 播放'}};$('#favorite').onclick=toggleFavorite;
  $('#full').onclick=async()=>{state.fullscreen=!state.fullscreen;await window.mibox.fullscreen(state.fullscreen);$('#full').textContent=state.fullscreen?'退出全屏':'⛶ 全屏'};$('#more').onclick=()=>$('#menu').classList.toggle('open');
  $('#video').onplaying=()=>{$('#loading').style.display='none';$('#toggle').textContent='Ⅱ 暂停'};$('#video').onpause=()=>$('#toggle').textContent='▶ 播放';$('#video').onerror=()=>{$('#loading').style.display='none';toast('播放器无法打开此频道')};
  $('#menu').onclick=async e=>{const a=e.target.dataset.action;if(!a)return;$('#menu').classList.remove('open');if(a==='update')loadSource(true);if(a==='test')testSources();if(a==='clear'){let n=0;for(const c of state.channels)if(state.availability.get(c.url)===false&&!state.blocked.has(c.url)){state.blocked.add(c.url);n++}persist();render();toast(`已隐藏 ${n} 个失效源`)}if(a==='restore'){const n=state.blocked.size;state.blocked.clear();persist();render();toast(`已恢复 ${n} 个源`)}if(a==='playlist')importM3U();if(a==='video')openLocal();if(a==='url'){const url=prompt('输入 MP4 或 M3U8 直播地址');if(/^https?:\/\//i.test(url||''))play({name:'自定义直播',group:'网络地址',url})}};
  document.addEventListener('click',e=>{if(!e.target.closest('#menu,#more'))$('#menu').classList.remove('open')});
  document.addEventListener('keydown',async e=>{if(e.key==='F11'){e.preventDefault();state.fullscreen=!state.fullscreen;await window.mibox.fullscreen(state.fullscreen);return}if(e.key==='Escape'){if(state.fullscreen){state.fullscreen=false;await window.mibox.fullscreen(false)}else $('#menu').classList.remove('open');return}if(e.key==='Enter'&&document.activeElement?.tagName==='BUTTON'){document.activeElement.click();return}if(!e.key.startsWith('Arrow'))return;const candidates=$$('.focusable').filter(x=>x.offsetParent!==null),active=document.activeElement;if(!candidates.includes(active)){candidates[0]?.focus();return}const a=active.getBoundingClientRect();let best,score=Infinity;for(const c of candidates){if(c===active)continue;const r=c.getBoundingClientRect(),dx=r.left-a.left,dy=r.top-a.top,h=e.key==='ArrowLeft'||e.key==='ArrowRight',ok=e.key==='ArrowRight'?dx>5:e.key==='ArrowLeft'?dx<-5:e.key==='ArrowDown'?dy>5:dy<-5;if(!ok)continue;const s=(h?Math.abs(dx):Math.abs(dy))+(h?Math.abs(dy):Math.abs(dx))*2;if(s<score){score=s;best=c}}if(best){e.preventDefault();best.focus();best.scrollIntoView({block:'nearest'})}});
}
async function init(){state.sources=await window.mibox.listSources();$('#source').innerHTML=state.sources.map(s=>`<option value="${s.id}">${s.name}</option>`).join('');bind();await loadSource(false);const tick=()=>$('#clock').textContent=new Date().toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});tick();setInterval(tick,30000)}init();
